### ISSUE TITLE
Bytecode mismatch on records

### ISSUE THREAD

**Issue by rlnt** [neoforged/ModDevGradle#179]
When looking at a class from a dependency mod that ships sources, the bytecode doesn't match when the class is a record.
It doesn't seem to matter which toolchain the dependency mod uses. I reproduced it with mods that use MDG, NeoGradle, and Arch Loom.

![Image](https://github.com/user-attachments/assets/6c01ad3b-c41a-466a-9cb6-a14152a01484)

MDG: 2.0.42-beta

IntelliJ IDEA 2024.2.3 (Ultimate Edition)
Build #IU-242.23339.11, built on September 25, 2024
Runtime version: 21.0.4+13-b509.17 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

**Comment by Matyrobbrt** [comment]
This is completely unrelated to gradle or any plugins for that matter. It's an issue with IntelliJ when it doesn't realise that the bytecode mismatch is caused by the methods generated implicitly by records.
