### ISSUE TITLE
Running command prints garbage symbols on Windows

### ISSUE THREAD

**Issue by Nightenom** [neoforged/ModDevGradle#8]
Running commands in Windows 11 cmd.exe might suffer from default charset not being utf-8, one can switch using `chcp 65001` but setting that globally is still beta (see first image in <https://stackoverflow.com/a/57134096>)
My default chcp is 852, but generally that depends on Windows language

`chcp 852`:
![image](https://github.com/neoforged/ModDevGradle/assets/17338378/10109e4e-6372-4a04-b912-b3e2ffccf862)

`chcp 65001`:
![image](https://github.com/neoforged/ModDevGradle/assets/17338378/60b0da28-dcb1-49ec-bf8d-076e4e4278d1)

**Comment by Gaming32** [comment]
I think the only real solution to this is to just not print these fancy characters under an unsupported encoding. Windows charsets don't support fancy characters like these, as they're all single byte charsets that don't support more than 127 characters beyond ASCII.
