### ISSUE TITLE
Problem with common modules when build with architectury

### ISSUE THREAD

**Issue by Stein-N** [neoforged/ModDevGradle#85]
ModDevGradle seems to have a problem with common builds of API Mods, when they where build with architectury loom or architectury itself.

I tried getting ShulkerBoxTooltip working but all Minecraft related classes/methods aren't mapped correctly/at all, they always show up as class_2561 for example. Also tried to get Accessories working and got the same problem with the mappings in common.
![image](https://github.com/neoforged/ModDevGradle/assets/128091790/65d7f30c-f525-4785-89d9-3377d5eeabc7)

But when i use the common module of MysticDrews Common Networking api the mapping gets applied correctly. So i assume when the common Module is built with VanillaGradle it works as intended.

**Comment by Stein-N** [comment]
As a workaround i can use the neoforge version of those mods, but this wouldn't be a good solution

**Comment by Matyrobbrt** [comment]
This is not a issue on our side, you shouldn't publish *common* artifacts in intermediary, we have no mod remapping as we fully use mojmaps, and even if we did, it wouldn't be from intermediary.

**Comment by Technici4n** [comment]
In fact, if you depend on `mysticdrew:common-networking-common:1.0.11-1.21`, you should get mojang mappings already.

**Comment by Stein-N** [comment]
My own little library mod wich is build with vanilla gradle also works perfectly fine, so i would assume it is an issue with Loom or arch loom then?

**Comment by Technici4n** [comment]
Well, the jar that is on mysticdrew's maven is definitely using mojang mappings (at least the one I linked). So I assume there is an issue with your setup?

**Comment by Stein-N** [comment]
MysticDrews API works fine and the mapping is correct, only the arch common modules are screwed/not mapped

**Comment by Technici4n** [comment]
Do you mind hopping on Discord in the `modder-support-gradle` channel? That might be easier to diagnose.

**Comment by Stein-N** [comment]
can i ping you?
