### ISSUE TITLE
Eclipse run configurations don't honor the Java toolchain version

### ISSUE THREAD

**Issue by ljfa-ag** [neoforged/ModDevGradle#98]
I'm not sure if this only affects Eclipse or if this is a more general problem. When importing the Gradle project into Eclipse, the run configs that are being generated are set to the workspace's default JVM, which in my case is 17, rather than the project's JVM 21. The result is that I can't directly run the configurations unless I change the run config's JVM:
![Bildschirmfoto vom 2024-07-12 09-51-22](https://github.com/user-attachments/assets/d0cb8529-57a8-47e1-90f5-105d2a7aab94)
Notice how it is set to "Alternate JRE". Neither ForgeGradle nor NeoGradle run configs were using this setting, they would use the "Project execution environment" setting instead, so they worked regardless of Eclipse's defaults.
As you can see, the project JVM is still set to the correct version as specified in build.gradle.

I tried it with MDK-1.21-ModDevGradle, only modified to change the ModDevGradle version to 1.0.1.

**Comment by ljfa-ag** [comment]
Sure:
![grafik](https://github.com/user-attachments/assets/ca688c93-cbe9-4ea3-b716-efcaa83d103a)
This is on Arch Linux with Eclipse 2024-06. I have OpenJDK 8, 17, 21 and latest (22) installed.

**Comment by Shadows-of-Fire** [comment]
@shartte note the comment [from ELC](https://github.com/neoforged/EclipseLaunchConfigs/blob/fe8c5287501df55bc594a7e64e4a99ec195dc470/src/main/java/net/neoforged/elc/configs/JavaApplicationLaunchConfig.java#L387-L403):
```java
        /**
         * Defines the JRE to use when executing the application. The definition must take the following three-part format, each part separated by a forward slash:
         * <ol>
         * <li>The header, which is "org.eclipse.jdt.launching.JRE_CONTAINER"</li>
         * <li>The VM type, which is one of "org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType" or "org.eclipse.jdt.launching.EEVMType"</li>
         * <li>The VM name, which is a user-specified value for a JVM in Eclipse, such as "jdk-17.0.5.8-hotspot"</li>
         * </ol>
         * For example, a full declaration may look like
         * "org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/jdk-17.0.5.8-hotspot"
         * <p>
         * E-Attribute type: String
         * <br>
         * Required: False
         * <br>
         * Default Value: The default JVM of the Eclipse project specified by {@link #ATTR_PROJECT_NAME}.
         */
```

Just setting it to `JavaSE-21` would be invalid and cause Eclipse to fallback to the default.  You will need to set it to the following magic string: `org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-21/`

As a test, @ljfa-ag could you set the value of `org.eclipse.jdt.launching.JRE_CONTAINER` in the run config file to the aforementioned value and see if eclipse properly picks up J21?  It works for me in my local testing.

**Comment by Shadows-of-Fire** [comment]
Though based on the broader context it may be better to just omit it and let it use the project default. We didn't supply this attribute in FG nor NG, and it is kinda brittle.

If the project default isn't set appropriately then a bunch of other things will be on fire (because Eclipse will fail to build the project)

**Comment by ljfa-ag** [comment]
> As a test, @ljfa-ag could you set the value of `org.eclipse.jdt.launching.JRE_CONTAINER` in the run config file to the aforementioned value and see if eclipse properly picks up J21? It works for me in my local testing.

Yup, that works for me as well.

**Comment by ljfa-ag** [comment]
No worries, thank you guys for the quick fix :)
